# Generated by Django 2.0 on 2020-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_subtitle', models.CharField(max_length=100)),
                ('event_desc', models.TextField(max_length=1000)),
                ('event_image', models.ImageField(upload_to='board/media')),
            ],
        ),
    ]
